name: build and push docker image

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: set docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract build version
        id: extract_version
        run: echo "BUILD_VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV

      - name: build docker image 
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github_actions:latest .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/github_actions:${{ env.BUILD_VERSION }} .
        
      
      - name: push docker image 
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/github_actions:latest 
          docker push ${{ secrets.DOCKER_USERNAME }}/github_actions:${{ env.BUILD_VERSION }} 
