name: Send Email on Push

on: [push]

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Send Email
        env:
          EMAIL: ${{ secrets.EMAIL }}
          GITHUB_ACTOR: ${{ github.actor }}
          REPO_NAME: ${{ github.repository }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          echo "User: $GITHUB_ACTOR"
          echo "Repository: $REPO_NAME"
          echo "Commit Hash: $COMMIT_HASH"
          # שליחת המייל באמצעות סקריפט או שירות API
