name: Send Email on Push
 #test
on: [push]
 
jobs:
  send-email-job:
    runs-on: ubuntu-latest
 
    env:
      MAIL_USERNAME: paormatan@gmail.com  # Replace with your email address
      TO_EMAIL: paormatan@gmail.com  # Replace with the recipient's email address
 
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3
 
    - name: Install msmtp
      run: sudo apt-get install -y msmtp
 
    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host smtp.gmail.com" >> ~/.msmtprc
        echo "port 587" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "user $MAIL_USERNAME" >> ~/.msmtprc    
        echo "password ${{ secrets.MAIL_PASSWORD }}" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
        echo "from $MAIL_USERNAME" >> ~/.msmtprc     
        echo "logfile ~/.msmtp.log" >> ~/.msmtprc
        chmod 600 ~/.msmtprc
 
    - name: Send Email
      run: |
        echo -e "From: $MAIL_USERNAME\nTo: $TO_EMAIL\nSubject: GitHub Push Notification\n\nWho pushed the code: ${{ github.actor }}\nRepository: ${{ github.repository }}\nCommit hash: ${{ github.sha }}" | msmtp --from=default --debug $TO_EMAIL
