name: Send Email on Push
 
on: [push]
 
jobs:
  send-email-job:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3
 
    - name: Install msmtp
      run: sudo apt-get install -y msmtp
 
    - name: Configure msmtp
      run: |
        echo "account default" > ~/.msmtprc
        echo "host smtp.gmail.com" >> ~/.msmtprc
        echo "port 587" >> ~/.msmtprc
        echo "auth on" >> ~/.msmtprc
        echo "user $MAIL_USERNAME" >> ~/.msmtprc
        echo "password ${{ secrets.MAIL_PASSWORD }}" >> ~/.msmtprc
        echo "tls on" >> ~/.msmtprc
        echo "tls_trust_file /etc/ssl/certs/ca-certificates.crt" >> ~/.msmtprc
        echo "from $MAIL_USERNAME" >> ~/.msmtprc
        echo "logfile ~/.msmtp.log" >> ~/.msmtprc
        chmod 600 ~/.msmtprc
 
    - name: Send Email
      env:
        GIT_AUTHOR: ${{ github.actor }}
        REPO_NAME: ${{ github.repository }}
        COMMIT_HASH: ${{ github.sha }}
        MAIL_USERNAME: $MAIL_USERNAME
        TO_EMAIL: $TO_EMAIL
      run: |
        echo -e "From: $MAIL_USERNAME\nTo: $TO_EMAIL\nSubject: GitHub Push Notification\n\nWho pushed the code: $GIT_AUTHOR\nRepository: $REPO_NAME\nCommit hash: $COMMIT_HASH" | msmtp --from=default $TO_EMAIL
