name: Send Email on Push

on: [push]

jobs:
  send-email-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v3

    - name: Send Email
      env:
        GIT_AUTHOR: ${{ github.actor }}
        REPO_NAME: ${{ github.repository }}
        COMMIT_HASH: ${{ github.sha }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        echo "Sending email to $TO_EMAIL"
        echo -e "Subject: GitHub Push Notification\n\nWho pushed the code: $GIT_AUTHOR\nRepository: $REPO_NAME\nCommit hash: $COMMIT_HASH" | sendmail -v $TO_EMAIL
